### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by PtrckM** [naworkcaj/betrayed#1]
Feature Request:
- able to join channel with password
 - only [master nick] can do commands

**Comment by naworkcaj** [comment]
I do have some recent changes to the kit, but not nearly close to being adequate enough to push them as I've been working on other things. You can expect a commit here in the next 2 or 3 weeks. I'll add these features in that commit. 🦃

**Comment by PtrckM** [comment]
customizable name for `.so`  filename

**Comment by naworkcaj** [comment]
Thanks for this. These feature requests have been made available in the most recent commit.
See the rootkit's configuration header for the first two requests.

For changing things such as the `.so` filename, at runtime, you can do something like: `SONAME=randomname.so ./install.sh` as each variable is set to a custom value unless otherwise specified by the user at runtime.
At some point I'll make the README better.
